#+TITLE: SystemHalted's Emacs Config

* Core

** Startup

#+begin_src emacs-lisp :tangle yes
;; -*- lexical-binding: t; -*-
  (setq inhibit-startup-screen t)
#+end_src


** Custom Settings

Let's protect the startup file from changes made through Emacs' =Customize= interface.
By default, it can write settings into initialization file. However, we want those saved
separately. The =custom.el= will be created only when =Customize= is used.

#+begin_src emacs-lisp :tangle yes
  (setq custom-file
        (expand-file-name "var/custom.el" user-emacs-directory))

  (make-directory (file-name-directory custom-file) t)

  (when (file-exists-p custom-file)
        (load custom-file))
#+end_src

** Packages

#+begin_src emacs-lisp :tangle yes
  ;; require loads a library unless it has already been loaded
  (require 'package)

  (setq package-archives
        '(("gnu" . "https://elpa.gnu.org/packages/")
  ("nongnu" . "https://elpa.nongnu.org/nongnu/")
        ("melpa" . "https://melpa.org/packages/")))

  (setq package-archive-priorities
        '(("gnu" . 30)
        ("nongnu" . 25)
        ("melpa" . 20)))

  (require 'use-package)
#+end_src

** Files
Do not make backup copies like =notes.org~=

#+begin_src emacs-lisp :tangle yes
  (let ((auto-save-dir
         (expand-file-name "var/auto-save" user-emacs-directory)))
        (make-directory auto-save-dir t)
        (setq make-backup-files nil
              auto-save-file-name-transforms
              (list (list ".*" auto-save-dir t))))
#+end_src

** Key Conventions

#+begin_src emacs-lisp :tangle yes
(electric-pair-mode 1)
#+end_src

* Interaction

** Minibuffer history

#+begin_src emacs-lisp :tangle yes
  ;; enable savhist-mode;
  ;; `:ensure nil` means it would use existing library
  (use-package savehist
    :ensure nil
    :config
    (savehist-mode 1))
#+end_src


** Vertico

Vertico display completion candidates vertically while keping
Emacs' existing matching system.

#+begin_src emacs-lisp :tangle yes
  (use-package vertico
    :ensure t
    :config
    (vertico-mode 1))
#+end_src

** Orderless

[[https://github.com/oantolin/orderless#overview][Orderless]] matches space-separated pieces in any order. For example,
=function describe= can match =describe-function=.

We make orderless as the completion style and basic provides a fallback for completion
tables that need it. Selecting the style enables its use.

#+begin_src emacs-lisp :tangle yes
  (use-package orderless
    :ensure t
    :custom
    (completion-styles '(orderless basic))
     (completion-category-overrides
      '((file (styles basic partial-completion)))))
#+end_src

** which-key

 #+begin_src emacs-lisp :tangle yes
    (use-package which-key
      :ensure t
      :config
      (which-key-mode 1))
  #+end_src

* Development

** Language Servers

*** Eglot

Eglot is used as LSP Client. It is included with Emacs provides
completion, go-to-definition, documentation, refactoring and diagnostics
when a server is available

#+begin_src emacs-lisp :tangle yes
    (use-package eglot
      :ensure nil
      :hook
        ((java-mode . eglot-ensure)
         (rust-mode . eglot-ensure)))
        ;; equivalent to   (add-hook 'java-mode-hook #'eglot-ensure)
        ;;  (add-hook 'rust-mode-hook #'eglot-ensure)
#+end_src

** Language Modes

*** Rust

#+begin_src emacs-lisp :tangle yes
  (use-package rust-mode
    :ensure t)
#+end_src

** Projectile

#+begin_src emacs-lisp :tangle yes
  (use-package projectile
    :ensure t
    :bind-keymap
    ("C-c p" . projectile-command-map)
    :config
    (projectile-mode 1))
#+end_src

** Yasnippet

#+begin_src emacs-lisp :tangle yes
  (use-package yasnippet
    :ensure t
    :hook
    ((prog-mode . yas-minor-mode)
     (org-mode . yas-minor-mode)))

  ;; for ready-made snippets
  (use-package yasnippet-snippets
    :ensure t
    :after yasnippet)

#+end_src

* Knowledge

** Org

Setup organicely and make Org aware of it.
The files is created in =inbox= first. If later, need migration,
=M-x dired-jump= and =R (dired-do-rename)= to push to destination path.

#+begin_src emacs-lisp :tangle yes

  (defun systemhalted/org-new-inbox-note ()
         "Create a new Org note in the Organicely inbox"
         (interactive)
         (find-file
          (expand-file-name
           (concat (read-string "Note Filename:") ".org")
           (expand-file-name "00-inbox/" org-directory))))

  (use-package org
     :ensure nil
     :custom
     (org-directory
      (expand-file-name "organicely" "~/Work"))
     :bind
     (("C-c c" . systemhalted/org-new-inbox-note)))
#+end_src


* Tools

** Magit

#+begin_src emacs-lisp :tangle yes
  (use-package magit
    :ensure t
    :bind
    (("C-x g" . magit-status)))

#+end_src
